# Project
group=xyz.milosworks
version=0.0.1-SNAPSHOT
# Common
id=untitled
modName=Untitled
authors=MilosWorks
# Review your options at https://choosealicense.com/.
license=See GitHub for more details.
description=KLibrary
# Gradle
org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8
org.gradle.configureondemand=true
org.gradle.caching=false
org.gradle.configuration-cache=false
org.gradle.parallel=true
# For local development, keeping the daemon on is much faster.
org.gradle.daemon=true
# Dokka
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
org.jetbrains.dokka.experimental.gradle.pluginMode.noWarn=true